### ISSUE TITLE
Dynamic attribute names

### ISSUE THREAD

**Issue by dmotz** [goto-bus-stop/babel-plugin-yo-yoify#13]
Right now dynamic attribute names don't work with this transform.

For example:
```javascript
const handler = isTouchDevice ? 'ontouchstart' : 'onmousedown'

return html`
  <div ${handler}=${() => console.log('hello')}></div>
`
```

**Comment by goto-bus-stop** [comment]
Hmm, yeah. This is a bit tough because the way attributes are compiled depends on what the attribute is:

 - `onclick` → `el.onclick = () => {}`
 - `disabled` → `el.setAttribute('disabled', 'disabled')`
 - `className=${xyz}` → `el.setAttribute('class', xyz)`
 - `onload` and `onunload` → `_onload(el, () => {}, () => {}, $uniqueId)`

So to compile dynamic attributes, you'd need a runtime that does the same. I'm not sure that that's something I really want to support… I'd suggest doing it manually instead:

```js
const el = html`
  <div />
`
if (isTouchDevice)
  el.ontouchstart = handler
else
  el.onmousedown = handler
return el

function handler () {
  console.log('hello')
}
```

It would definitely be useful to throw a more descriptive error if a template value is used in an unexpected position though.

**Comment by dmotz** [comment]
Makes total sense. I wonder if there's a clever way to statically hint at the attribute type at compile time (though this would probably involve changing the DSL).

Thanks for the explanation. A compile time warning would be useful, but for now I'll close this issue.

**Comment by goto-bus-stop** [comment]
Looks like [shama/yo-yoify](https://github.com/shama/yo-yoify) does support this now to some extent (though attributes only), I wanna try to at least be on par with it. Working on that in #17
